language: node_js

<<<<<<< HEAD
node_js:
  - 'stable'
  - 'lts/*'

cache:
  directories:
    - node_modules

# before_script:
#     - "npm i -g gatsby-cli"
#     - "yarn"

script:
  - gatsby build
=======
os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "7"
  - "8"

script:
  - npm install
  - npm run lint
>>>>>>> d914f91... Initial commit from gatsby: (https://github.com/EAB-Sales/eab-sales-site.git)
